spring.datasource.url=jdbc:mysql://localhost:3306/mobile_accessories
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=StringStackEcommerceJwtSecretKey2026MustBe256BitsLong!!
jwt.expiration-ms=86400000

razorpay.key-id=rzp_test_TKvVr7P40NJFJR
razorpay.key-secret=0xj6RzuumLSiNF3VrLF1QiHx

server.port=8080
